language: go
go:
- 1.7.1
env:
  global:
  - secure: wubgHkMpY9bxSMZALkV1GWs4GpfMBDjXRYiPMOaNthcfIkUQ6sZwgKYyUv5SWzYH2XiUX3Hnag5P1hLsFyP41DpaZyJfSByAFlD5uYtB/XUCz8EER0+gQCw7BS8nHh2BvTvc+2g47mSyBjdkA/ZdACdFSLy/0A7X4NcBqNJVUtN4AxCNXDypBI9elZ6xu02sCYQyDA6Qq0MFcO9Z7aJ5V2lEAkQcyH9XD/rELETKlFhw+e3hi6CtWvUgP37Gq++wA5kDR4V+/Xk8iKYSNXgifSvnoJg5RKklB9Pa7iDeaZINJDHZyrj6ZV2VVimxWJoQo7JiO5FV495b7owrCPrRewK5m+7btxN6HxhB4p1sTrQfQQ/C7tWquKZLfIW4wb+pHufi6fnZ2vwrEVl3eepygrywNBsI3BWR6NWPOa3q3x5QdrGeS5UAAEeq97PmlmBxlNYNgf9vvlEW5nn04HCj8XL66+6u7FR6YdZNuYEstRvAAceXRdcFcnQzIDkPw/ClQl8GfQIl2ba2fjeKVXxJrDTW9vaK4WA+F6481xt36YYCQUVDxOj7wJQSetPhzw7H+Q5D6y6BgnUpj29ofnIAqAmfJJ0jkibk95MHQTAp2Qjbi8PXytT2OSNEb/sszBCjxjSGoTyzuocOucxR9pi3Fb7GVjR5bb0HYYKWa+YZwGE=
  - secure: 2XibSt0fSYM3S5ti/WIzUCRukcL3qbHzb+CAC/Bw+QBxvYXuLOqCxIzftVoyDa/XJzqVMFb5nkXvUrI4G87T+yq9/uBAHSCxObx9Apuk0rM42l0nGpG0UbsNeOB7t6ZoDzIEwqCTykzM9JOewNylbglsMavDBk0FVAOo53EEbcGMnXRDO6y6mFzyrtTYnCyHavX/EhCJFa83v83IIjGkK9odKPNNCdCZF0qYAe0kSizs1uxeDvSTvOPGX8sIqBNNRrVg5LRHB3sRcBs4LITEyrXO4G7QGBA95BxmahIZ1SSUgM/H+x3srLDfEcRXu5WNSzqMech2nvF2DAD74ydU1UrCWoQUC49sZ8cHRA8CIz91uU/QAnbmMVoeMBL43nAJhrenqzvke7gKbxcHz21bIUKVj5FsVFLPx73xSZpibzLYiQEUSuvqnA3IQmi81TavZzPH096irPESYKa+Plry1f4zppPJd0coUxV2K2WZ5B1vAgPgVilCBFAhT8cb5iuPTolOJzaqv6uSVHZKjOb0qFIHpMcbNYfqqJY5nOmZFH+IqO9q0GVccEkkatreRVXDvM1KpNSc/E957SbFz160jhjAksuaw+R3mYM6xlPvnLc88vaMsDoaXbKFAKVwTjYmR34mJDssEXQLA9DE8NDMW2R1ZpxqyFMIsTBbh0o+Cyc=
install:
- go get -v github.com/spf13/hugo
- git config --global user.email "${EMAIL}"
- git config --global user.name "Steve Good"
script:
- git clone https://github.com/stevegood/stevegood.github.io.git
- cd stevegood.github.io
- git config credential.helper "store --file=.git/credentials"
- echo "https://stevegood:${GH_TOKEN}@github.com" > .git/credentials
- cd ..
- hugo -d stevegood.github.io
- cd stevegood.github.io
- git status
- git add .
- git commit -m "Updated content"
- git push origin master
