title = "Steve Good"
languageCode = "en-us"
baseurl = "//www.stevegood.rocks/"
theme = "casper"
MetaDataFormat = "yaml"

DisqusShortname = "stevegood"

[params]
  description = "Developer - Photographer - Human"
  cover = "images/cover.jpg"
  author = "Steve Good"
  authorlocation = "San Diego, CA"
  authorlocationLink = "https://www.google.com/maps/place/San+Diego,+CA/@32.8244745,-117.2352455,11z/data=!3m1!4b1!4m5!3m4!1s0x80d9530fad921e4b:0xd3a21fdfd15df79!8m2!3d32.715738!4d-117.1610838"
  authorwebsite = "https://stevegood.rocks"
  bio= "Professional software engineer, amatuer photographer, and part-time mountain biker."
  logo = "images/steve-avatar-dark.png"
  googleAnalyticsUserID = "UA-26916811-1"
  githubName = "stevegood"
  twitterName = "stevegood"
  hideHUGOSupport = true

[[menu.main]]
  name = "Blog"
  url = "/"
  weight = -200
[[menu.main]]
  name = "About Me"
  url = "/about"
  weight = -180
[[menu.main]]
  name = "Deep Core"
  url = "/deep_core"
  weight = -140