title = "Steve Good"
languageCode = "en-us"
baseurl = "http://www.stevegood.rocks/"
theme = "casper"
MetaDataFormat = "yaml"

DisqusShortname = "stevegood"

[params]
  description = "Developer - Photographer - Human"
  cover = "images/cover.jpg"
  author = "Steve Good"
  authorlocation = "San Diego, CA"
  authorwebsite = "http://stevegood.rocks"
  bio= "Professional software engineer, amatuer photographer, and part-time mountain biker."
  logo = "images/steve-avatar-dark.png"
  googleAnalyticsUserID = "UA-26916811-1"
  githubName = "stevegood"
  twitterName = "stevegood"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = true

[[menu.main]]
  name = "Home"
  url = "/"
  weight = -200
# [[menu.main]]
#   name = "About"
#   url = "/about/"
#   weight = -180
